import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/Container";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";
import ToastifyContainer from "@/components/ToastifyContainer";

export const metadata: Metadata = {
  title: {
    default: "The Planet Blog - made with next.js",
    template: "%s | The Planet Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.StrictMode>
      <html lang="en">
        <body>
          <Container>
            <Header />

            {children}

            <Footer />
          </Container>

          <ToastifyContainer />
        </body>
      </html>
    </React.StrictMode>
  );
}
