import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/Container";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: "The Planet Blog - made with next.js",
    template: "%s | The Planet Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />

          {children}

          <footer>
            <h2 className="text-6x1 font-bold text-center py-8">
              Aqui é o footer
            </h2>
          </footer>
        </Container>
      </body>
    </html>
  );
}
